application: fakesubwayapis
version: 2
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*/CVS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

handlers:
- url: .*
  script: main.py
